--- Inserting data into the table
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY) VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );
INSERT INTO CUSTOMERS VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

--- Selecting data from the table
SELECT * FROM CUSTOMERS;
SELECT column1, column2 FROM CUSTOMERS;
SELECT * FROM CUSTOMERS WHERE ID = 1;
SELECT * FROM CUSTOMERS WHERE ID = 1 AND AGE = 32;
SELECT * AS alias FROM CUSTOMERS WHERE AGE > 30;

--- Select into a table
SELECT * INTO CUSTOMERS_TEMP FROM CUSTOMERS;
SELECT * INTO CUSTOMERS_TEMP FROM CUSTOMERS WHERE ID = 1;

--- Inserting data into the table
INSERT INTO CUSTOMERS_TEMP (ID,NAME,AGE,ADDRESS,SALARY) VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

--- Update data 
UPDATE CUSTOMERS SET ADDRESS = 'Pune' WHERE ID = 6;

--- Delete data 
DELETE FROM CUSTOMERS_TEMP WHERE ID = 1;

--- Sorting data
SELECT * FROM CUSTOMERS ORDER BY ID;
SELECT * FROM CUSTOMERS ORDER BY AGE DESC;
SELECT * FROM CUSTOMERS ORDER BY AGE ASC;