--- Where
SELECT ID, NAME, SALARY FROM CUSTOMERS 
WHERE SALARY > 2000;


SELECT ID, NAME, SALARY FROM CUSTOMERS
WHERE SALARY > 2000 AND SALARY < 3000;

--- Top 
SELECT TOP 10 ID, NAME, SALARY FROM CUSTOMERS;

--- Distinct
SELECT DISTINCT ID, NAME, SALARY FROM CUSTOMERS;

--- Order by
SELECT ID, NAME, SALARY FROM CUSTOMERS ORDER BY SALARY ASC|DESC;

--- Group by
SELECT ID, NAME, SALARY FROM CUSTOMERS GROUP BY SALARY;

--- Having
SELECT ID, NAME, SALARY FROM CUSTOMERS GROUP BY SALARY HAVING SALARY > 2000;

--- And & Or
SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 AND SALARY < 3000;
SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 2000 OR SALARY < 3000;

--- Boolean
SELECT * FROM CARS WHERE IsRed = TRUE;
SELECT * FROM CARS WHERE IsRed = 1;

--- Like
SELECT * FROM CARS WHERE Name LIKE 'A%';
/*
WHERE SALARY LIKE '200%'
Finds any values that start with 200.

WHERE SALARY LIKE '%200%'
Finds any values that have 200 in any position.

WHERE SALARY LIKE '_00%'
Finds any values that have 00 in the second and third positions.

WHERE SALARY LIKE '2_%_%'
Finds any values that start with 2 and are at least 3 characters in length.

WHERE SALARY LIKE '%2'
Finds any values that end with 2.

WHERE SALARY LIKE '_2%3'
Finds any values that have a 2 in the second position and end with a 3.

WHERE SALARY LIKE '2___3'
Finds any values in a five-digit number that start with 2 and end with 3.
*/

--- In
SELECT * FROM CUSTOMERS WHERE NAME IN ('Khilan', 'Hardik', 'Muffy');

--- Any
SELECT * FROM CUSTOMERS WHERE SALARY > ANY (SELECT SALARY FROM CUSTOMERS WHERE SALARY > 2000);

--- All
SELECT * FROM CUSTOMERS WHERE SALARY > ALL (SELECT SALARY FROM CUSTOMERS WHERE SALARY > 2000);

--- Exists
SELECT * FROM CUSTOMERS WHERE EXISTS (SELECT * FROM CUSTOMERS WHERE SALARY > 2000);

--- Case
SELECT CASE WHEN SALARY > 2000 THEN 'High' ELSE 'Low' END AS 'Status' FROM CUSTOMERS;

--- Not
SELECT * FROM CUSTOMERS WHERE NOT SALARY > 2000;

--- Not Equal
SELECT * FROM CUSTOMERS WHERE ID <> 1;
SELECT * FROM CUSTOMERS WHERE ID != 1;

--- Is Null
SELECT * FROM CUSTOMERS WHERE ADDRESS IS NULL;
SELECT * FROM CUSTOMERS WHERE ADDRESS IS NOT NULL;

--- Between
SELECT * FROM CUSTOMERS WHERE AGE BETWEEN 20 AND 30;
SELECT * FROM CUSTOMERS WHERE AGE NOT BETWEEN 20 AND 30;

--- Alias
SELECT ID, NAME, SALARY FROM CUSTOMERS AS C;