--- Union
SELECT * FROM CUSTOMERS WHERE SALARY > 2000 UNION SELECT * FROM CUSTOMERS WHERE SALARY < 2000;

--- Union All
SELECT * FROM CUSTOMERS WHERE SALARY > 2000 UNION ALL SELECT * FROM CUSTOMERS WHERE SALARY < 2000;

--- Intersect
SELECT NAME, AGE, HOBBY FROM STUDENTS_HOBBY INTERSECT SELECT NAME, AGE, HOBBY FROM STUDENTS;

--- Except
SELECT NAME, AGE, HOBBY FROM STUDENTS_HOBBY EXCEPT SELECT NAME, AGE, HOBBY FROM STUDENTS;

--- Join
SELECT * FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--- Inner Join
SELECT * FROM CUSTOMERS INNER JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--- Left Join
SELECT * FROM CUSTOMERS LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--- Right Join
SELECT * FROM CUSTOMERS RIGHT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--- Full Join
SELECT * FROM CUSTOMERS FULL JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--- Cross Join
SELECT * FROM CUSTOMERS CROSS JOIN ORDERS;

--- Natural Join
SELECT * FROM CUSTOMERS NATURAL JOIN ORDERS;

--- Outer Join
SELECT * FROM CUSTOMERS LEFT OUTER JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

--- Self Join
SELECT * FROM CUSTOMERS AS C1 JOIN CUSTOMERS AS C2 ON C1.ID = C2.ID;

--- Delete Join
DELETE a
FROM CUSTOMERS AS a INNER JOIN ORDERS AS b
ON a.ID = b.CUSTOMER_ID;

--- Update Join
UPDATE a
SET a.NAME = b.NAME
FROM CUSTOMERS AS a INNER JOIN ORDERS AS b
ON a.ID = b.CUSTOMER_ID;

--- Insert Join
INSERT INTO CUSTOMERS (ID, NAME, SALARY)
SELECT b.ID, b.NAME, b.SALARY
FROM CUSTOMERS AS a INNER JOIN ORDERS AS b
ON a.ID = b.CUSTOMER_ID;